trigger: none
pr:
- master
- stable

schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - master
    - stable

variables:
  BASE_BRANCH: "master"
  CACHE_S3_PREFIX: "stack-nightly"
  CACHE_S3_VERSION: "v0.1.4"
  S3_BUCKET: "fpco-public-cache"
  AWS_REGION: "us-east-1"

jobs:
# - template: ./.azure/azure-nightly-template-osx.yml
#   parameters:
#     name: macOS
#     vmImage: macOS-10.14
#     os: osx

# - template: ./.azure/azure-nightly-template-linux.yml
#   parameters:
#     name: Linux
#     vmImage: ubuntu-16.04
#     os: linux

# - template: ./.azure/azure-nightly-template-windows.yml
#   parameters:
#    name: Windows
#    vmImage: vs2017-win2016
#    os: windows

- template: ./.azure/azure-nightly-template-alpine.yml
  parameters:
   name: AlpineLinux64
   vmImage: ubuntu-16.04
   os: alpine-linux
   containerImage: jeffhappily/alpine-glibc-bash:alpine-3.11_glibc-2.30@sha256:4b557ab2f1ac7dada16273f6c95cd02428ac49b66de545b4a5d92a8f80ece610

- template: ./.azure/azure-nightly-template-alpine.yml
  parameters:
   name: AlpineLinux32
   vmImage: ubuntu-16.04
   os: alpine-linux
   containerImage: jeffhappily/alpine-glibc-bash:alpine-3.11_glibc-2.30@sha256:18a2d83177e5d40fcb534512f48ece3b12f3d59e91fd058ce1cb96e11bad29a6
