jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  variables:
  - group: AWS_Keys
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: SSH@0
    inputs:
      sshEndpoint: AARCH64
        # privateKey: $(AARCH64_PRIVATE_KEY)
      runOptions: 'inline' # Options: commands, script, inline
      #commands: # Required when runOptions == Commands
      # scriptPath: './script/build.sh'
      inline: 'uname -m; echo "Hello"' # Required when runOptions == Inline
      #args: # Optional
      #failOnStdErr: true # Optional
